/**
 * fingerprint_events [array]
 */

const fp = {
    // @event: 2410
    "123": [
        16,
        1024,
        4096,
        7,
        12,
        120,
        [
            23,
            127,
            127
        ]
    ],

    // @event: 2412
    "307": [
        1,
        1024,
        1,
        1,
        4
    ],
    "464": [
        255,
        255,
        255,
        255,
        192,
        192,
        192,
        255,
        244,
        244,
        244,
        255,
        53,
        53,
        53,
        255
    ],

    // @event: 3211
    "513": [
        "wGTOxqzMyudn2adM",
        "17",
        "c",
        "GHQGDHLIAUNHI"
    ],

    // @event: 604
    "687": [
        "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
        8,
        16,
        "fr-FR",
        [
            "fr-FR",
            "fr",
            "en-US",
            "en"
        ],
        "Win32",
        null,
        [
            "Google Chrome 117",
            "Not;A=Brand 8",
            "Chromium 117"
        ],
        false,
        "Windows",
        2,
        5,
        true,
        false,
        50,
        false,
        false,
        true,
        "[object Keyboard]",
        false,
        false
    ],

    "701": 1116,

    // @event: 1402
    "787": [
        "Europe/Paris",
        -60,
        -60,
        -3203647761000,
        "heure d’été d’Europe centrale",
        "fr"
    ],
    "820": [
        [
            122,
            [
                122,
                122,
                122,
                255,
                122,
                122,
                122,
                255,
                122,
                122,
                122,
                255,
                122,
                122,
                122,
                255
            ]
        ],
        [
            [
                11,
                0,
                0,
                95.96875,
                15,
                4,
                96.765625
            ],
            [
                [
                    12,
                    0,
                    -1,
                    113.125,
                    17,
                    4,
                    113
                ],
                [
                    11,
                    0,
                    0,
                    111,
                    12,
                    4,
                    111
                ],
                [
                    11,
                    0,
                    0,
                    95.96875,
                    15,
                    4,
                    96.765625
                ],
                [
                    11,
                    0,
                    0,
                    95.96875,
                    15,
                    4,
                    96.765625
                ],
                [
                    11,
                    0,
                    0,
                    95.96875,
                    15,
                    4,
                    96.765625
                ],
                [
                    11,
                    0,
                    0,
                    95.96875,
                    15,
                    4,
                    96.765625
                ],
                [
                    11,
                    0,
                    0,
                    95.96875,
                    15,
                    4,
                    96.765625
                ],
                [
                    11,
                    0,
                    0,
                    95.96875,
                    15,
                    4,
                    96.765625
                ],
                [
                    12,
                    0,
                    0,
                    109.640625,
                    14,
                    3,
                    110.1953125
                ]
            ]
        ]
    ],
    "845": 308443.80000000075,

    // @event: 1403
    "935": [
        "gZzZkMLQ0bmD3Z=MvAmn",
        "e",
        "6",
        "IAGVHPDOLNFJP"
    ],
    "59f": 57,
    "1ab": [
        "-0.7108118501064332,1.9275814160560204e-50,-0.7181630308570678,1.6182817135715877",
        37,
        "toString() radix argument must be between 2 and 36",
        "Invalid array length"
    ],
    "46e": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAR9JREFUOE/N1MEqRVEUxvHfHRoYMZOSiaEH8AgewAAzpZBShpQYGijFC2DgDTCVBzA08QbGplo6S7vt3NqnrnJGp9Na3/p/69v7jEz4GU1YzxDBFVxhDbM4xjo+Sqghgk1mUnAGd13HFo6w0BEEzT128VKpBmU877jFRgoudU3LeO1svRXN2XhWfIueExxiFTfx3md5qiu6LvYTzZfYRw6KIUGWzr5nlYJRcNoRPOEBF2Mok25vXCghNocDfKJMNIlKkZ0+uiTssxO2g+65shSDpzGPX3QpGDSbBV26jDO2iDqISPy83l02xQ6HCObxiiH1EfoJZYjlJsFQrkMJu7GG+mo1C2YI290uHvvuKZoFm+5pS9Gf/RxahjfV/H/CL60pQ+2uFC+LAAAAAElFTkSuQmCC",
    "8f4": [
        14,
        4,
        1,
        41.3203125,
        17,
        4,
        44.2890625
    ],

    // @event: 1107
    "7ac": [
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        288.671875,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        324.609375,
        266,
        297.953125,
        266,
        252.734375,
        266,
        274.609375,
        266,
        187.609375,
        266,
        187.609375,
        266,
        154.40625,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        172.265625,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266,
        274.609375,
        266
    ],

    // @event: 211
    "5f1": [
        -6.172840118408203,
        -20.710678100585938,
        120.71067810058594,
        -20.710678100585938,
        141.42135620117188,
        120.71067810058594,
        -20.710678100585938,
        141.42135620117188,
        -20.710678100585938,
        -20.710678100585938,
        0,
        0,
        300,
        150,
        false,
        [
            0,
            15,
            33,
            34,
            35,
            37,
            39,
            75
        ]
    ],

    // @event: 3401
    "0fe": [
        [
            "HTML",
            2
        ],
        [
            "HEAD",
            5
        ],
        [
            "TITLE",
            0
        ],
        [
            "META",
            0
        ],
        [
            "META",
            0
        ],
        [
            "META",
            0
        ],
        [
            "STYLE",
            0
        ],
        [
            "BODY",
            2
        ],
        [
            "SCRIPT",
            0
        ],
        [
            "DIV",
            4
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            5
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            111
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "SPAN",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            3
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            1
        ],
        [
            "DIV",
            3
        ],
        [
            "DIV",
            2
        ],
        [
            "H2",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            2
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ],
        [
            "DIV",
            0
        ]
    ],

    // @event: 3403
    "d02": [
        [
            [
                "https://newassets.hcaptcha.com/captcha/v1/28ff887/hcaptcha.js",
                0,
                5
            ]
        ],
        [
            [
                "*",
                84,
                9
            ]
        ]
    ],

    // @event: 803
    "07c": [
        1,
        4,
        5,
        7,
        9,
        12,
        20,
        21,
        24,
        25,
        29
    ],

    // @event: 2801?
    "2b7": [
        277114314453,
        277114314460,
        277114314451,
        357114314456,
        277114314452,
        554228628898,
        57114314443,
        717114314371391,
        554228628897,
        277114314456,
        1108457257862,
        277114314450,
        554228628919,
        277114314460,
        277114314451
    ],
    
    // @event: 2805
    "a10": [
        [
            277114314453,
            277114314460,
            277114314451,
            357114314456,
            277114314452,
            554228628898,
            57114314443,
            717114314371391,
            554228628897,
            277114314456,
            1108457257862,
            277114314450,
            554228628919,
            277114314460,
            277114314451
        ],
        false
    ],
    // @event: 107
    "f99": [
        3440,
        1440,
        3440,
        1392,
        24,
        24,
        false,
        0,
        1,
        1592,
        1399,
        true,
        true,
        true,
        false
    ],

    // @event: 302
    "d97": {
        "ActiveBorder": "rgb(0, 0, 0)",
        "ActiveCaption": "rgb(0, 0, 0)",
        "ActiveText": "rgb(0, 102, 204)",
        "AppWorkspace": "rgb(255, 255, 255)",
        "Background": "rgb(255, 255, 255)",
        "ButtonBorder": "rgb(0, 0, 0)",
        "ButtonFace": "rgb(240, 240, 240)",
        "ButtonHighlight": "rgb(240, 240, 240)",
        "ButtonShadow": "rgb(240, 240, 240)",
        "ButtonText": "rgb(0, 0, 0)",
        "Canvas": "rgb(255, 255, 255)",
        "CanvasText": "rgb(0, 0, 0)",
        "CaptionText": "rgb(0, 0, 0)",
        "Field": "rgb(255, 255, 255)",
        "FieldText": "rgb(0, 0, 0)",
        "GrayText": "rgb(109, 109, 109)",
        "Highlight": "rgb(0, 120, 215)",
        "HighlightText": "rgb(255, 255, 255)",
        "InactiveBorder": "rgb(0, 0, 0)",
        "InactiveCaption": "rgb(255, 255, 255)",
        "InactiveCaptionText": "rgb(128, 128, 128)",
        "InfoBackground": "rgb(255, 255, 255)",
        "InfoText": "rgb(0, 0, 0)",
        "LinkText": "rgb(0, 102, 204)",
        "Mark": "rgb(255, 255, 0)",
        "MarkText": "rgb(0, 0, 0)",
        "Menu": "rgb(255, 255, 255)",
        "MenuText": "rgb(0, 0, 0)",
        "Scrollbar": "rgb(255, 255, 255)",
        "ThreeDDarkShadow": "rgb(0, 0, 0)",
        "ThreeDFace": "rgb(240, 240, 240)",
        "ThreeDHighlight": "rgb(0, 0, 0)",
        "ThreeDLightShadow": "rgb(0, 0, 0)",
        "ThreeDShadow": "rgb(0, 0, 0)",
        "VisitedText": "rgb(0, 102, 204)",
        "Window": "rgb(255, 255, 255)",
        "WindowFrame": "rgb(0, 0, 0)",
        "WindowText": "rgb(0, 0, 0)",
        "caption": "16px Arial",
        "icon": "16px Arial",
        "menu": "12px \"Segoe UI\"",
        "message-box": "16px Arial",
        "small-caption": "12px \"Segoe UI\"",
        "status-bar": "12px \"Segoe UI\""
    },

    // @event: 303
    "89d": [
        "Arial",
        "\"Segoe UI\""
    ],

    // @event: 301 ?
    "19e": [
        "cssText",
        "length",
        "parentRule",
        "cssFloat",
        "getPropertyPriority",
        "getPropertyValue",
        "item",
        "removeProperty",
        "setProperty",
        "constructor",
        "accentColor",
        "additiveSymbols",
        "alignContent",
        "alignItems",
        "alignSelf",
        "alignmentBaseline",
        "all",
        "animation",
        "animationComposition",
        "animationDelay",
        "animationDirection",
        "animationDuration",
        "animationFillMode",
        "animationIterationCount",
        "animationName",
        "animationPlayState",
        "animationRange",
        "animationRangeEnd",
        "animationRangeStart",
        "animationTimeline",
        "animationTimingFunction",
        "appRegion",
        "appearance",
        "ascentOverride",
        "aspectRatio",
        "backdropFilter",
        "backfaceVisibility",
        "background",
        "backgroundAttachment",
        "backgroundBlendMode",
        "backgroundClip",
        "backgroundColor",
        "backgroundImage",
        "backgroundOrigin",
        "backgroundPosition",
        "backgroundPositionX",
        "backgroundPositionY",
        "backgroundRepeat",
        "backgroundRepeatX",
        "backgroundRepeatY",
        "backgroundSize",
        "basePalette",
        "baselineShift",
        "baselineSource",
        "blockSize",
        "border",
        "borderBlock",
        "borderBlockColor",
        "borderBlockEnd",
        "borderBlockEndColor",
        "borderBlockEndStyle",
        "borderBlockEndWidth",
        "borderBlockStart",
        "borderBlockStartColor",
        "borderBlockStartStyle",
        "borderBlockStartWidth",
        "borderBlockStyle",
        "borderBlockWidth",
        "borderBottom",
        "borderBottomColor",
        "borderBottomLeftRadius",
        "borderBottomRightRadius",
        "borderBottomStyle",
        "borderBottomWidth",
        "borderCollapse",
        "borderColor",
        "borderEndEndRadius",
        "borderEndStartRadius",
        "borderImage",
        "borderImageOutset",
        "borderImageRepeat",
        "borderImageSlice",
        "borderImageSource",
        "borderImageWidth",
        "borderInline",
        "borderInlineColor",
        "borderInlineEnd",
        "borderInlineEndColor",
        "borderInlineEndStyle",
        "borderInlineEndWidth",
        "borderInlineStart",
        "borderInlineStartColor",
        "borderInlineStartStyle",
        "borderInlineStartWidth",
        "borderInlineStyle",
        "borderInlineWidth",
        "borderLeft",
        "borderLeftColor",
        "borderLeftStyle",
        "borderLeftWidth",
        "borderRadius",
        "borderRight",
        "borderRightColor",
        "borderRightStyle",
        "borderRightWidth",
        "borderSpacing",
        "borderStartEndRadius",
        "borderStartStartRadius",
        "borderStyle",
        "borderTop",
        "borderTopColor",
        "borderTopLeftRadius",
        "borderTopRightRadius",
        "borderTopStyle",
        "borderTopWidth",
        "borderWidth",
        "bottom",
        "boxShadow",
        "boxSizing",
        "breakAfter",
        "breakBefore",
        "breakInside",
        "bufferedRendering",
        "captionSide",
        "caretColor",
        "clear",
        "clip",
        "clipPath",
        "clipRule",
        "color",
        "colorInterpolation",
        "colorInterpolationFilters",
        "colorRendering",
        "colorScheme",
        "columnCount",
        "columnFill",
        "columnGap",
        "columnRule",
        "columnRuleColor",
        "columnRuleStyle",
        "columnRuleWidth",
        "columnSpan",
        "columnWidth",
        "columns",
        "contain",
        "containIntrinsicBlockSize",
        "containIntrinsicHeight",
        "containIntrinsicInlineSize",
        "containIntrinsicSize",
        "containIntrinsicWidth",
        "container",
        "containerName",
        "containerType",
        "content",
        "contentVisibility",
        "counterIncrement",
        "counterReset",
        "counterSet",
        "cursor",
        "cx",
        "cy",
        "d",
        "descentOverride",
        "direction",
        "display",
        "dominantBaseline",
        "emptyCells",
        "fallback",
        "fill",
        "fillOpacity",
        "fillRule",
        "filter",
        "flex",
        "flexBasis",
        "flexDirection",
        "flexFlow",
        "flexGrow",
        "flexShrink",
        "flexWrap",
        "float",
        "floodColor",
        "floodOpacity",
        "font",
        "fontDisplay",
        "fontFamily",
        "fontFeatureSettings",
        "fontKerning",
        "fontOpticalSizing",
        "fontPalette",
        "fontSize",
        "fontStretch",
        "fontStyle",
        "fontSynthesis",
        "fontSynthesisSmallCaps",
        "fontSynthesisStyle",
        "fontSynthesisWeight",
        "fontVariant",
        "fontVariantAlternates",
        "fontVariantCaps",
        "fontVariantEastAsian",
        "fontVariantLigatures",
        "fontVariantNumeric",
        "fontVariantPosition",
        "fontVariationSettings",
        "fontWeight",
        "forcedColorAdjust",
        "gap",
        "grid",
        "gridArea",
        "gridAutoColumns",
        "gridAutoFlow",
        "gridAutoRows",
        "gridColumn",
        "gridColumnEnd",
        "gridColumnGap",
        "gridColumnStart",
        "gridGap",
        "gridRow",
        "gridRowEnd",
        "gridRowGap",
        "gridRowStart",
        "gridTemplate",
        "gridTemplateAreas",
        "gridTemplateColumns",
        "gridTemplateRows",
        "height",
        "hyphenateCharacter",
        "hyphenateLimitChars",
        "hyphens",
        "imageOrientation",
        "imageRendering",
        "inherits",
        "initialLetter",
        "initialValue",
        "inlineSize",
        "inset",
        "insetBlock",
        "insetBlockEnd",
        "insetBlockStart",
        "insetInline",
        "insetInlineEnd",
        "insetInlineStart",
        "isolation",
        "justifyContent",
        "justifyItems",
        "justifySelf",
        "left",
        "letterSpacing",
        "lightingColor",
        "lineBreak",
        "lineGapOverride",
        "lineHeight",
        "listStyle",
        "listStyleImage",
        "listStylePosition",
        "listStyleType",
        "margin",
        "marginBlock",
        "marginBlockEnd",
        "marginBlockStart",
        "marginBottom",
        "marginInline",
        "marginInlineEnd",
        "marginInlineStart",
        "marginLeft",
        "marginRight",
        "marginTop",
        "marker",
        "markerEnd",
        "markerMid",
        "markerStart",
        "mask",
        "maskType",
        "mathDepth",
        "mathShift",
        "mathStyle",
        "maxBlockSize",
        "maxHeight",
        "maxInlineSize",
        "maxWidth",
        "minBlockSize",
        "minHeight",
        "minInlineSize",
        "minWidth",
        "mixBlendMode",
        "negative",
        "objectFit",
        "objectPosition",
        "objectViewBox",
        "offset",
        "offsetAnchor",
        "offsetDistance",
        "offsetPath",
        "offsetPosition",
        "offsetRotate",
        "opacity",
        "order",
        "orphans",
        "outline",
        "outlineColor",
        "outlineOffset",
        "outlineStyle",
        "outlineWidth",
        "overflow",
        "overflowAnchor",
        "overflowClipMargin",
        "overflowWrap",
        "overflowX",
        "overflowY",
        "overlay",
        "overrideColors",
        "overscrollBehavior",
        "overscrollBehaviorBlock",
        "overscrollBehaviorInline",
        "overscrollBehaviorX",
        "overscrollBehaviorY",
        "pad",
        "padding",
        "paddingBlock",
        "paddingBlockEnd",
        "paddingBlockStart",
        "paddingBottom",
        "paddingInline",
        "paddingInlineEnd",
        "paddingInlineStart",
        "paddingLeft",
        "paddingRight",
        "paddingTop",
        "page",
        "pageBreakAfter",
        "pageBreakBefore",
        "pageBreakInside",
        "pageOrientation",
        "paintOrder",
        "perspective",
        "perspectiveOrigin",
        "placeContent",
        "placeItems",
        "placeSelf",
        "pointerEvents",
        "position",
        "prefix",
        "quotes",
        "r",
        "range",
        "resize",
        "right",
        "rotate",
        "rowGap",
        "rubyPosition",
        "rx",
        "ry",
        "scale",
        "scrollBehavior",
        "scrollMargin",
        "scrollMarginBlock",
        "scrollMarginBlockEnd",
        "scrollMarginBlockStart",
        "scrollMarginBottom",
        "scrollMarginInline",
        "scrollMarginInlineEnd",
        "scrollMarginInlineStart",
        "scrollMarginLeft",
        "scrollMarginRight",
        "scrollMarginTop",
        "scrollPadding",
        "scrollPaddingBlock",
        "scrollPaddingBlockEnd",
        "scrollPaddingBlockStart",
        "scrollPaddingBottom",
        "scrollPaddingInline",
        "scrollPaddingInlineEnd",
        "scrollPaddingInlineStart",
        "scrollPaddingLeft",
        "scrollPaddingRight",
        "scrollPaddingTop",
        "scrollSnapAlign",
        "scrollSnapStop",
        "scrollSnapType",
        "scrollTimeline",
        "scrollTimelineAxis",
        "scrollTimelineName",
        "scrollbarGutter",
        "shapeImageThreshold",
        "shapeMargin",
        "shapeOutside",
        "shapeRendering",
        "size",
        "sizeAdjust",
        "speak",
        "speakAs",
        "src",
        "stopColor",
        "stopOpacity",
        "stroke",
        "strokeDasharray",
        "strokeDashoffset",
        "strokeLinecap",
        "strokeLinejoin",
        "strokeMiterlimit",
        "strokeOpacity",
        "strokeWidth",
        "suffix",
        "symbols",
        "syntax",
        "system",
        "tabSize",
        "tableLayout",
        "textAlign",
        "textAlignLast",
        "textAnchor",
        "textCombineUpright",
        "textDecoration",
        "textDecorationColor",
        "textDecorationLine",
        "textDecorationSkipInk",
        "textDecorationStyle",
        "textDecorationThickness",
        "textEmphasis",
        "textEmphasisColor",
        "textEmphasisPosition",
        "textEmphasisStyle",
        "textIndent",
        "textOrientation",
        "textOverflow",
        "textRendering",
        "textShadow",
        "textSizeAdjust",
        "textTransform",
        "textUnderlineOffset",
        "textUnderlinePosition",
        "textWrap",
        "timelineScope",
        "top",
        "touchAction",
        "transform",
        "transformBox",
        "transformOrigin",
        "transformStyle",
        "transition",
        "transitionBehavior",
        "transitionDelay",
        "transitionDuration",
        "transitionProperty",
        "transitionTimingFunction",
        "translate",
        "unicodeBidi",
        "unicodeRange",
        "userSelect",
        "vectorEffect",
        "verticalAlign",
        "viewTimeline",
        "viewTimelineAxis",
        "viewTimelineInset",
        "viewTimelineName",
        "viewTransitionName",
        "visibility",
        "webkitAlignContent",
        "webkitAlignItems",
        "webkitAlignSelf",
        "webkitAnimation",
        "webkitAnimationDelay",
        "webkitAnimationDirection",
        "webkitAnimationDuration",
        "webkitAnimationFillMode",
        "webkitAnimationIterationCount",
        "webkitAnimationName",
        "webkitAnimationPlayState",
        "webkitAnimationTimingFunction",
        "webkitAppRegion",
        "webkitAppearance",
        "webkitBackfaceVisibility",
        "webkitBackgroundClip",
        "webkitBackgroundOrigin",
        "webkitBackgroundSize",
        "webkitBorderAfter",
        "webkitBorderAfterColor",
        "webkitBorderAfterStyle",
        "webkitBorderAfterWidth",
        "webkitBorderBefore",
        "webkitBorderBeforeColor",
        "webkitBorderBeforeStyle",
        "webkitBorderBeforeWidth",
        "webkitBorderBottomLeftRadius",
        "webkitBorderBottomRightRadius",
        "webkitBorderEnd",
        "webkitBorderEndColor",
        "webkitBorderEndStyle",
        "webkitBorderEndWidth",
        "webkitBorderHorizontalSpacing",
        "webkitBorderImage",
        "webkitBorderRadius",
        "webkitBorderStart",
        "webkitBorderStartColor",
        "webkitBorderStartStyle",
        "webkitBorderStartWidth",
        "webkitBorderTopLeftRadius",
        "webkitBorderTopRightRadius",
        "webkitBorderVerticalSpacing",
        "webkitBoxAlign",
        "webkitBoxDecorationBreak",
        "webkitBoxDirection",
        "webkitBoxFlex",
        "webkitBoxOrdinalGroup",
        "webkitBoxOrient",
        "webkitBoxPack",
        "webkitBoxReflect",
        "webkitBoxShadow",
        "webkitBoxSizing",
        "webkitClipPath",
        "webkitColumnBreakAfter",
        "webkitColumnBreakBefore",
        "webkitColumnBreakInside",
        "webkitColumnCount",
        "webkitColumnGap",
        "webkitColumnRule",
        "webkitColumnRuleColor",
        "webkitColumnRuleStyle",
        "webkitColumnRuleWidth",
        "webkitColumnSpan",
        "webkitColumnWidth",
        "webkitColumns",
        "webkitFilter",
        "webkitFlex",
        "webkitFlexBasis",
        "webkitFlexDirection",
        "webkitFlexFlow",
        "webkitFlexGrow",
        "webkitFlexShrink",
        "webkitFlexWrap",
        "webkitFontFeatureSettings",
        "webkitFontSmoothing",
        "webkitHyphenateCharacter",
        "webkitJustifyContent",
        "webkitLineBreak",
        "webkitLineClamp",
        "webkitLocale",
        "webkitLogicalHeight",
        "webkitLogicalWidth",
        "webkitMarginAfter",
        "webkitMarginBefore",
        "webkitMarginEnd",
        "webkitMarginStart",
        "webkitMask",
        "webkitMaskBoxImage",
        "webkitMaskBoxImageOutset",
        "webkitMaskBoxImageRepeat",
        "webkitMaskBoxImageSlice",
        "webkitMaskBoxImageSource",
        "webkitMaskBoxImageWidth",
        "webkitMaskClip",
        "webkitMaskComposite",
        "webkitMaskImage",
        "webkitMaskOrigin",
        "webkitMaskPosition",
        "webkitMaskPositionX",
        "webkitMaskPositionY",
        "webkitMaskRepeat",
        "webkitMaskRepeatX",
        "webkitMaskRepeatY",
        "webkitMaskSize",
        "webkitMaxLogicalHeight",
        "webkitMaxLogicalWidth",
        "webkitMinLogicalHeight",
        "webkitMinLogicalWidth",
        "webkitOpacity",
        "webkitOrder",
        "webkitPaddingAfter",
        "webkitPaddingBefore",
        "webkitPaddingEnd",
        "webkitPaddingStart",
        "webkitPerspective",
        "webkitPerspectiveOrigin",
        "webkitPerspectiveOriginX",
        "webkitPerspectiveOriginY",
        "webkitPrintColorAdjust",
        "webkitRtlOrdering",
        "webkitRubyPosition",
        "webkitShapeImageThreshold",
        "webkitShapeMargin",
        "webkitShapeOutside",
        "webkitTapHighlightColor",
        "webkitTextCombine",
        "webkitTextDecorationsInEffect",
        "webkitTextEmphasis",
        "webkitTextEmphasisColor",
        "webkitTextEmphasisPosition",
        "webkitTextEmphasisStyle",
        "webkitTextFillColor",
        "webkitTextOrientation",
        "webkitTextSecurity",
        "webkitTextSizeAdjust",
        "webkitTextStroke",
        "webkitTextStrokeColor",
        "webkitTextStrokeWidth",
        "webkitTransform",
        "webkitTransformOrigin",
        "webkitTransformOriginX",
        "webkitTransformOriginY",
        "webkitTransformOriginZ",
        "webkitTransformStyle",
        "webkitTransition",
        "webkitTransitionDelay",
        "webkitTransitionDuration",
        "webkitTransitionProperty",
        "webkitTransitionTimingFunction",
        "webkitUserDrag",
        "webkitUserModify",
        "webkitUserSelect",
        "webkitWritingMode",
        "whiteSpace",
        "whiteSpaceCollapse",
        "widows",
        "width",
        "willChange",
        "wordBreak",
        "wordSpacing",
        "wordWrap",
        "writingMode",
        "x",
        "y",
        "zIndex",
        "zoom"
    ],

    // @event: 304
    "67e": 623,

    // @event: 1401
    "b2e": "Europe/Paris",

    // @event: 3503
    "63e": 1695511062952,

    // @event: 3501
    "ba2": [
        [
            "navigation:newassets.hcaptcha.com",
            0.19999999925494194,
            5.399999998509884
        ],
        [
            "script:newassets.hcaptcha.com",
            0.14999999850988388,
            5.150000000372529
        ],
        [
            "xmlhttprequest:hcaptcha.com",
            0,
            39.20000000298023
        ]
    ],

    // @event: 3502
    "8b0": 0.19999999925494194,

    // @event: 3505
    "61e": 6.199999999254942,

    // @event: 401
    "6f5": [
        0.09999999776482582,
        30
    ],

    // @event: 402
    "7e0": [
        "Object",
        "Function",
        "Array",
        "Number",
        "parseFloat",
        "parseInt",
        "Infinity",
        "NaN",
        "undefined",
        "Boolean",
        "String",
        "Symbol",
        "Date",
        "Promise",
        "RegExp",
        "Error",
        "AggregateError",
        "EvalError",
        "RangeError",
        "ReferenceError",
        "SyntaxError",
        "TypeError",
        "URIError",
        "globalThis",
        "JSON",
        "Math",
        "Intl",
        "ArrayBuffer",
        "Atomics",
        "Uint8Array",
        "Int8Array",
        "Uint16Array",
        "Int16Array",
        "Uint32Array",
        "Int32Array",
        "Float32Array",
        "Float64Array",
        "Uint8ClampedArray",
        "BigUint64Array",
        "BigInt64Array",
        "DataView",
        "Map",
        "BigInt",
        "Set",
        "WeakMap",
        "WeakSet",
        "Proxy",
        "Reflect",
        "FinalizationRegistry",
        "WeakRef",
        "decodeURI",
        "decodeURIComponent",
        "encodeURI",
        "encodeURIComponent",
        "escape",
        "unescape",
        "eval",
        "isFinite",
        "isNaN",
        "console",
        "Option",
        "Image",
        "Audio",
        "webkitURL",
        "webkitRTCPeerConnection",
        "webkitMediaStream",
        "WebKitMutationObserver",
        "WebKitCSSMatrix",
        "XSLTProcessor",
        "XPathResult",
        "XPathExpression",
        "XPathEvaluator",
        "XMLSerializer",
        "XMLHttpRequestUpload",
        "XMLHttpRequestEventTarget",
        "XMLHttpRequest",
        "XMLDocument",
        "WritableStreamDefaultWriter",
        "WritableStreamDefaultController",
        "WritableStream",
        "Worker",
        "Window",
        "WheelEvent",
        "WebSocket",
        "WebGLVertexArrayObject",
        "WebGLUniformLocation",
        "WebGLTransformFeedback",
        "WebGLTexture",
        "WebGLSync",
        "WebGLShaderPrecisionFormat",
        "WebGLShader",
        "WebGLSampler",
        "WebGLRenderingContext",
        "WebGLRenderbuffer",
        "WebGLQuery",
        "WebGLProgram",
        "WebGLFramebuffer",
        "WebGLContextEvent",
        "WebGLBuffer",
        "WebGLActiveInfo",
        "WebGL2RenderingContext",
        "WaveShaperNode",
        "VisualViewport",
        "VirtualKeyboardGeometryChangeEvent",
        "ValidityState",
        "VTTCue",
        "UserActivation",
        "URLSearchParams",
        "URLPattern",
        "URL",
        "UIEvent",
        "TrustedTypePolicyFactory",
        "TrustedTypePolicy",
        "TrustedScriptURL",
        "TrustedScript",
        "TrustedHTML",
        "TreeWalker",
        "TransitionEvent",
        "TransformStreamDefaultController",
        "TransformStream",
        "TrackEvent",
        "TouchList",
        "TouchEvent",
        "Touch",
        "TimeRanges",
        "TextTrackList",
        "TextTrackCueList",
        "TextTrackCue",
        "TextTrack",
        "TextMetrics",
        "TextEvent",
        "TextEncoderStream",
        "TextEncoder",
        "TextDecoderStream",
        "TextDecoder",
        "Text",
        "TaskSignal",
        "TaskPriorityChangeEvent",
        "TaskController",
        "TaskAttributionTiming",
        "SyncManager",
        "SubmitEvent",
        "StyleSheetList",
        "StyleSheet",
        "StylePropertyMapReadOnly",
        "StylePropertyMap",
        "StorageEvent",
        "Storage",
        "StereoPannerNode",
        "StaticRange",
        "SourceBufferList",
        "SourceBuffer",
        "ShadowRoot",
        "Selection",
        "SecurityPolicyViolationEvent",
        "ScriptProcessorNode",
        "ScreenOrientation",
        "Screen",
        "Scheduling",
        "Scheduler",
        "SVGViewElement",
        "SVGUseElement",
        "SVGUnitTypes",
        "SVGTransformList",
        "SVGTransform",
        "SVGTitleElement",
        "SVGTextPositioningElement",
        "SVGTextPathElement",
        "SVGTextElement",
        "SVGTextContentElement",
        "SVGTSpanElement",
        "SVGSymbolElement",
        "SVGSwitchElement",
        "SVGStyleElement",
        "SVGStringList",
        "SVGStopElement",
        "SVGSetElement",
        "SVGScriptElement",
        "SVGSVGElement",
        "SVGRectElement",
        "SVGRect",
        "SVGRadialGradientElement",
        "SVGPreserveAspectRatio",
        "SVGPolylineElement",
        "SVGPolygonElement",
        "SVGPointList",
        "SVGPoint",
        "SVGPatternElement",
        "SVGPathElement",
        "SVGNumberList",
        "SVGNumber",
        "SVGMetadataElement",
        "SVGMatrix",
        "SVGMaskElement",
        "SVGMarkerElement",
        "SVGMPathElement",
        "SVGLinearGradientElement",
        "SVGLineElement",
        "SVGLengthList",
        "SVGLength",
        "SVGImageElement",
        "SVGGraphicsElement",
        "SVGGradientElement",
        "SVGGeometryElement",
        "SVGGElement",
        "SVGForeignObjectElement",
        "SVGFilterElement",
        "SVGFETurbulenceElement",
        "SVGFETileElement",
        "SVGFESpotLightElement",
        "SVGFESpecularLightingElement",
        "SVGFEPointLightElement",
        "SVGFEOffsetElement",
        "SVGFEMorphologyElement",
        "SVGFEMergeNodeElement",
        "SVGFEMergeElement",
        "SVGFEImageElement",
        "SVGFEGaussianBlurElement",
        "SVGFEFuncRElement",
        "SVGFEFuncGElement",
        "SVGFEFuncBElement",
        "SVGFEFuncAElement",
        "SVGFEFloodElement",
        "SVGFEDropShadowElement",
        "SVGFEDistantLightElement",
        "SVGFEDisplacementMapElement",
        "SVGFEDiffuseLightingElement",
        "SVGFEConvolveMatrixElement",
        "SVGFECompositeElement",
        "SVGFEComponentTransferElement",
        "SVGFEColorMatrixElement",
        "SVGFEBlendElement",
        "SVGEllipseElement",
        "SVGElement",
        "SVGDescElement",
        "SVGDefsElement",
        "SVGComponentTransferFunctionElement",
        "SVGClipPathElement",
        "SVGCircleElement",
        "SVGAnimationElement",
        "SVGAnimatedTransformList",
        "SVGAnimatedString",
        "SVGAnimatedRect",
        "SVGAnimatedPreserveAspectRatio",
        "SVGAnimatedNumberList",
        "SVGAnimatedNumber",
        "SVGAnimatedLengthList",
        "SVGAnimatedLength",
        "SVGAnimatedInteger",
        "SVGAnimatedEnumeration",
        "SVGAnimatedBoolean",
        "SVGAnimatedAngle",
        "SVGAnimateTransformElement",
        "SVGAnimateMotionElement",
        "SVGAnimateElement",
        "SVGAngle",
        "SVGAElement",
        "Response",
        "ResizeObserverSize",
        "ResizeObserverEntry",
        "ResizeObserver",
        "Request",
        "ReportingObserver",
        "ReadableStreamDefaultReader",
        "ReadableStreamDefaultController",
        "ReadableStreamBYOBRequest",
        "ReadableStreamBYOBReader",
        "ReadableStream",
        "ReadableByteStreamController",
        "Range",
        "RadioNodeList",
        "RTCTrackEvent",
        "RTCStatsReport",
        "RTCSessionDescription",
        "RTCSctpTransport",
        "RTCRtpTransceiver",
        "RTCRtpSender",
        "RTCRtpReceiver",
        "RTCPeerConnectionIceEvent",
        "RTCPeerConnectionIceErrorEvent",
        "RTCPeerConnection",
        "RTCIceTransport",
        "RTCIceCandidate",
        "RTCErrorEvent",
        "RTCError",
        "RTCEncodedVideoFrame",
        "RTCEncodedAudioFrame",
        "RTCDtlsTransport",
        "RTCDataChannelEvent",
        "RTCDataChannel",
        "RTCDTMFToneChangeEvent",
        "RTCDTMFSender",
        "RTCCertificate",
        "PromiseRejectionEvent",
        "ProgressEvent",
        "Profiler",
        "ProcessingInstruction",
        "PopStateEvent",
        "PointerEvent",
        "PluginArray",
        "Plugin",
        "PictureInPictureWindow",
        "PictureInPictureEvent",
        "PeriodicWave",
        "PerformanceTiming",
        "PerformanceServerTiming",
        "PerformanceResourceTiming",
        "PerformancePaintTiming",
        "PerformanceObserverEntryList",
        "PerformanceObserver",
        "PerformanceNavigationTiming",
        "PerformanceNavigation",
        "PerformanceMeasure",
        "PerformanceMark",
        "PerformanceLongTaskTiming",
        "PerformanceEventTiming",
        "PerformanceEntry",
        "PerformanceElementTiming",
        "Performance",
        "Path2D",
        "PannerNode",
        "PageTransitionEvent",
        "OverconstrainedError",
        "OscillatorNode",
        "OffscreenCanvasRenderingContext2D",
        "OffscreenCanvas",
        "OfflineAudioContext",
        "OfflineAudioCompletionEvent",
        "NodeList",
        "NodeIterator",
        "NodeFilter",
        "Node",
        "NetworkInformation",
        "Navigator",
        "NavigationTransition",
        "NavigationHistoryEntry",
        "NavigationDestination",
        "NavigationCurrentEntryChangeEvent",
        "Navigation",
        "NavigateEvent",
        "NamedNodeMap",
        "MutationRecord",
        "MutationObserver",
        "MouseEvent",
        "MimeTypeArray",
        "MimeType",
        "MessagePort",
        "MessageEvent",
        "MessageChannel",
        "MediaStreamTrackProcessor",
        "MediaStreamTrackGenerator",
        "MediaStreamTrackEvent",
        "MediaStreamTrack",
        "MediaStreamEvent",
        "MediaStreamAudioSourceNode",
        "MediaStreamAudioDestinationNode",
        "MediaStream",
        "MediaSourceHandle",
        "MediaSource",
        "MediaRecorder",
        "MediaQueryListEvent",
        "MediaQueryList",
        "MediaList",
        "MediaError",
        "MediaEncryptedEvent",
        "MediaElementAudioSourceNode",
        "MediaCapabilities",
        "MathMLElement",
        "Location",
        "LayoutShiftAttribution",
        "LayoutShift",
        "LargestContentfulPaint",
        "KeyframeEffect",
        "KeyboardEvent",
        "IntersectionObserverEntry",
        "IntersectionObserver",
        "InputEvent",
        "InputDeviceInfo",
        "InputDeviceCapabilities",
        "ImageData",
        "ImageCapture",
        "ImageBitmapRenderingContext",
        "ImageBitmap",
        "IdleDeadline",
        "IIRFilterNode",
        "IDBVersionChangeEvent",
        "IDBTransaction",
        "IDBRequest",
        "IDBOpenDBRequest",
        "IDBObjectStore",
        "IDBKeyRange",
        "IDBIndex",
        "IDBFactory",
        "IDBDatabase",
        "IDBCursorWithValue",
        "IDBCursor",
        "History",
        "Headers",
        "HashChangeEvent",
        "HTMLVideoElement",
        "HTMLUnknownElement",
        "HTMLUListElement",
        "HTMLTrackElement",
        "HTMLTitleElement",
        "HTMLTimeElement",
        "HTMLTextAreaElement",
        "HTMLTemplateElement",
        "HTMLTableSectionElement",
        "HTMLTableRowElement",
        "HTMLTableElement",
        "HTMLTableColElement",
        "HTMLTableCellElement",
        "HTMLTableCaptionElement",
        "HTMLStyleElement",
        "HTMLSpanElement",
        "HTMLSourceElement",
        "HTMLSlotElement",
        "HTMLSelectElement",
        "HTMLScriptElement",
        "HTMLQuoteElement",
        "HTMLProgressElement",
        "HTMLPreElement",
        "HTMLPictureElement",
        "HTMLParamElement",
        "HTMLParagraphElement",
        "HTMLOutputElement",
        "HTMLOptionsCollection",
        "HTMLOptionElement",
        "HTMLOptGroupElement",
        "HTMLObjectElement",
        "HTMLOListElement",
        "HTMLModElement",
        "HTMLMeterElement",
        "HTMLMetaElement",
        "HTMLMenuElement",
        "HTMLMediaElement",
        "HTMLMarqueeElement",
        "HTMLMapElement",
        "HTMLLinkElement",
        "HTMLLegendElement",
        "HTMLLabelElement",
        "HTMLLIElement",
        "HTMLInputElement",
        "HTMLImageElement",
        "HTMLIFrameElement",
        "HTMLHtmlElement",
        "HTMLHeadingElement",
        "HTMLHeadElement",
        "HTMLHRElement",
        "HTMLFrameSetElement",
        "HTMLFrameElement",
        "HTMLFormElement",
        "HTMLFormControlsCollection",
        "HTMLFontElement",
        "HTMLFieldSetElement",
        "HTMLEmbedElement",
        "HTMLElement",
        "HTMLDocument",
        "HTMLDivElement",
        "HTMLDirectoryElement",
        "HTMLDialogElement",
        "HTMLDetailsElement",
        "HTMLDataListElement",
        "HTMLDataElement",
        "HTMLDListElement",
        "HTMLCollection",
        "HTMLCanvasElement",
        "HTMLButtonElement",
        "HTMLBodyElement",
        "HTMLBaseElement",
        "HTMLBRElement",
        "HTMLAudioElement",
        "HTMLAreaElement",
        "HTMLAnchorElement",
        "HTMLAllCollection",
        "GeolocationPositionError",
        "GeolocationPosition",
        "GeolocationCoordinates",
        "Geolocation",
        "GamepadHapticActuator",
        "GamepadEvent",
        "GamepadButton",
        "Gamepad",
        "GainNode",
        "FormDataEvent",
        "FormData",
        "FontFaceSetLoadEvent",
        "FontFace",
        "FocusEvent",
        "FileReader",
        "FileList",
        "File",
        "FeaturePolicy",
        "External",
        "EventTarget",
        "EventSource",
        "EventCounts",
        "Event",
        "ErrorEvent",
        "ElementInternals",
        "Element",
        "DynamicsCompressorNode",
        "DragEvent",
        "DocumentType",
        "DocumentFragment",
        "Document",
        "DelayNode",
        "DecompressionStream",
        "DataTransferItemList",
        "DataTransferItem",
        "DataTransfer",
        "DOMTokenList",
        "DOMStringMap",
        "DOMStringList",
        "DOMRectReadOnly",
        "DOMRectList",
        "DOMRect",
        "DOMQuad",
        "DOMPointReadOnly",
        "DOMPoint",
        "DOMParser",
        "DOMMatrixReadOnly",
        "DOMMatrix",
        "DOMImplementation",
        "DOMException",
        "DOMError",
        "CustomStateSet",
        "CustomEvent",
        "CustomElementRegistry",
        "Crypto",
        "CountQueuingStrategy",
        "ConvolverNode",
        "ConstantSourceNode",
        "CompressionStream",
        "CompositionEvent",
        "Comment",
        "CloseEvent",
        "ClipboardEvent",
        "CharacterData",
        "ChannelSplitterNode",
        "ChannelMergerNode",
        "CanvasRenderingContext2D",
        "CanvasPattern",
        "CanvasGradient",
        "CanvasCaptureMediaStreamTrack",
        "CSSVariableReferenceValue",
        "CSSUnparsedValue",
        "CSSUnitValue",
        "CSSTranslate",
        "CSSTransformValue",
        "CSSTransformComponent",
        "CSSSupportsRule",
        "CSSStyleValue",
        "CSSStyleSheet",
        "CSSStyleRule",
        "CSSStyleDeclaration",
        "CSSSkewY",
        "CSSSkewX",
        "CSSSkew",
        "CSSScale",
        "CSSRuleList",
        "CSSRule",
        "CSSRotate",
        "CSSPropertyRule",
        "CSSPositionValue",
        "CSSPerspective",
        "CSSPageRule",
        "CSSNumericValue",
        "CSSNumericArray",
        "CSSNamespaceRule",
        "CSSMediaRule",
        "CSSMatrixComponent",
        "CSSMathValue",
        "CSSMathSum",
        "CSSMathProduct",
        "CSSMathNegate",
        "CSSMathMin",
        "CSSMathMax",
        "CSSMathInvert",
        "CSSMathClamp",
        "CSSLayerStatementRule",
        "CSSLayerBlockRule",
        "CSSKeywordValue",
        "CSSKeyframesRule",
        "CSSKeyframeRule",
        "CSSImportRule",
        "CSSImageValue",
        "CSSGroupingRule",
        "CSSFontPaletteValuesRule",
        "CSSFontFaceRule",
        "CSSCounterStyleRule",
        "CSSContainerRule",
        "CSSConditionRule",
        "CSS",
        "CDATASection",
        "ByteLengthQueuingStrategy",
        "BroadcastChannel",
        "BlobEvent",
        "Blob",
        "BiquadFilterNode",
        "BeforeUnloadEvent",
        "BeforeInstallPromptEvent",
        "BaseAudioContext",
        "BarProp",
        "AudioWorkletNode",
        "AudioSinkInfo",
        "AudioScheduledSourceNode",
        "AudioProcessingEvent",
        "AudioParamMap",
        "AudioParam",
        "AudioNode",
        "AudioListener",
        "AudioDestinationNode",
        "AudioContext",
        "AudioBufferSourceNode",
        "AudioBuffer",
        "Attr",
        "AnimationEvent",
        "AnimationEffect",
        "Animation",
        "AnalyserNode",
        "AbstractRange",
        "AbortSignal",
        "AbortController",
        "window",
        "self",
        "document",
        "name",
        "location",
        "customElements",
        "history",
        "navigation",
        "locationbar",
        "menubar",
        "personalbar",
        "scrollbars",
        "statusbar",
        "toolbar",
        "status",
        "closed",
        "frames",
        "length",
        "top",
        "opener",
        "parent",
        "frameElement",
        "navigator",
        "origin",
        "external",
        "screen",
        "innerWidth",
        "innerHeight",
        "scrollX",
        "pageXOffset",
        "scrollY",
        "pageYOffset",
        "visualViewport",
        "screenX",
        "screenY",
        "outerWidth",
        "outerHeight",
        "devicePixelRatio",
        "event",
        "clientInformation",
        "offscreenBuffering",
        "screenLeft",
        "screenTop",
        "styleMedia",
        "onsearch",
        "isSecureContext",
        "trustedTypes",
        "performance",
        "onappinstalled",
        "onbeforeinstallprompt",
        "crypto",
        "indexedDB",
        "sessionStorage",
        "localStorage",
        "onbeforexrselect",
        "onabort",
        "onbeforeinput",
        "onblur",
        "oncancel",
        "oncanplay",
        "oncanplaythrough",
        "onchange",
        "onclick",
        "onclose",
        "oncontextlost",
        "oncontextmenu",
        "oncontextrestored",
        "oncuechange",
        "ondblclick",
        "ondrag",
        "ondragend",
        "ondragenter",
        "ondragleave",
        "ondragover",
        "ondragstart",
        "ondrop",
        "ondurationchange",
        "onemptied",
        "onended",
        "onerror",
        "onfocus",
        "onformdata",
        "oninput",
        "oninvalid",
        "onkeydown",
        "onkeypress",
        "onkeyup",
        "onload",
        "onloadeddata",
        "onloadedmetadata",
        "onloadstart",
        "onmousedown",
        "onmouseenter",
        "onmouseleave",
        "onmousemove",
        "onmouseout",
        "onmouseover",
        "onmouseup",
        "onmousewheel",
        "onpause",
        "onplay",
        "onplaying",
        "onprogress",
        "onratechange",
        "onreset",
        "onresize",
        "onscroll",
        "onsecuritypolicyviolation",
        "onseeked",
        "onseeking",
        "onselect",
        "onslotchange",
        "onstalled",
        "onsubmit",
        "onsuspend",
        "ontimeupdate",
        "ontoggle",
        "onvolumechange",
        "onwaiting",
        "onwebkitanimationend",
        "onwebkitanimationiteration",
        "onwebkitanimationstart",
        "onwebkittransitionend",
        "onwheel",
        "onauxclick",
        "ongotpointercapture",
        "onlostpointercapture",
        "onpointerdown",
        "onpointermove",
        "onpointerrawupdate",
        "onpointerup",
        "onpointercancel",
        "onpointerover",
        "onpointerout",
        "onpointerenter",
        "onpointerleave",
        "onselectstart",
        "onselectionchange",
        "onanimationend",
        "onanimationiteration",
        "onanimationstart",
        "ontransitionrun",
        "ontransitionstart",
        "ontransitionend",
        "ontransitioncancel",
        "onafterprint",
        "onbeforeprint",
        "onbeforeunload",
        "onhashchange",
        "onlanguagechange",
        "onmessage",
        "onmessageerror",
        "onoffline",
        "ononline",
        "onpagehide",
        "onpageshow",
        "onpopstate",
        "onrejectionhandled",
        "onstorage",
        "onunhandledrejection",
        "onunload",
        "crossOriginIsolated",
        "scheduler",
        "alert",
        "atob",
        "blur",
        "btoa",
        "cancelAnimationFrame",
        "cancelIdleCallback",
        "captureEvents",
        "clearInterval",
        "clearTimeout",
        "close",
        "confirm",
        "createImageBitmap",
        "fetch",
        "find",
        "focus",
        "getComputedStyle",
        "getSelection",
        "matchMedia",
        "moveBy",
        "moveTo",
        "open",
        "postMessage",
        "print",
        "prompt",
        "queueMicrotask",
        "releaseEvents",
        "reportError",
        "requestAnimationFrame",
        "requestIdleCallback",
        "resizeBy",
        "resizeTo",
        "scroll",
        "scrollBy",
        "scrollTo",
        "setInterval",
        "setTimeout",
        "stop",
        "structuredClone",
        "webkitCancelAnimationFrame",
        "webkitRequestAnimationFrame",
        "chrome",
        "WebAssembly",
        "fence",
        "caches",
        "cookieStore",
        "ondevicemotion",
        "ondeviceorientation",
        "ondeviceorientationabsolute",
        "launchQueue",
        "sharedStorage",
        "documentPictureInPicture",
        "onbeforematch",
        "onbeforetoggle",
        "AbsoluteOrientationSensor",
        "Accelerometer",
        "AudioWorklet",
        "BatteryManager",
        "Cache",
        "CacheStorage",
        "Clipboard",
        "ClipboardItem",
        "CookieChangeEvent",
        "CookieStore",
        "CookieStoreManager",
        "Credential",
        "CredentialsContainer",
        "CryptoKey",
        "DeviceMotionEvent",
        "DeviceMotionEventAcceleration",
        "DeviceMotionEventRotationRate",
        "DeviceOrientationEvent",
        "FederatedCredential",
        "GPU",
        "GPUAdapter",
        "GPUAdapterInfo",
        "GPUBindGroup",
        "GPUBindGroupLayout",
        "GPUBuffer",
        "GPUBufferUsage",
        "GPUCanvasContext",
        "GPUColorWrite",
        "GPUCommandBuffer",
        "GPUCommandEncoder",
        "GPUCompilationInfo",
        "GPUCompilationMessage",
        "GPUComputePassEncoder",
        "GPUComputePipeline",
        "GPUDevice",
        "GPUDeviceLostInfo",
        "GPUError",
        "GPUExternalTexture",
        "GPUInternalError",
        "GPUMapMode",
        "GPUOutOfMemoryError",
        "GPUPipelineError",
        "GPUPipelineLayout",
        "GPUQuerySet",
        "GPUQueue",
        "GPURenderBundle",
        "GPURenderBundleEncoder",
        "GPURenderPassEncoder",
        "GPURenderPipeline",
        "GPUSampler",
        "GPUShaderModule",
        "GPUShaderStage",
        "GPUSupportedFeatures",
        "GPUSupportedLimits",
        "GPUTexture",
        "GPUTextureUsage",
        "GPUTextureView",
        "GPUUncapturedErrorEvent",
        "GPUValidationError",
        "GravitySensor",
        "Gyroscope",
        "Keyboard",
        "KeyboardLayoutMap",
        "LinearAccelerationSensor",
        "Lock",
        "LockManager",
        "MIDIAccess",
        "MIDIConnectionEvent",
        "MIDIInput",
        "MIDIInputMap",
        "MIDIMessageEvent",
        "MIDIOutput",
        "MIDIOutputMap",
        "MIDIPort",
        "MediaDeviceInfo",
        "MediaDevices",
        "MediaKeyMessageEvent",
        "MediaKeySession",
        "MediaKeyStatusMap",
        "MediaKeySystemAccess",
        "MediaKeys",
        "NavigationPreloadManager",
        "NavigatorManagedData",
        "OrientationSensor",
        "PasswordCredential",
        "RelativeOrientationSensor",
        "Sanitizer",
        "ScreenDetailed",
        "ScreenDetails",
        "Sensor",
        "SensorErrorEvent",
        "ServiceWorker",
        "ServiceWorkerContainer",
        "ServiceWorkerRegistration",
        "StorageManager",
        "SubtleCrypto",
        "VirtualKeyboard",
        "WGSLLanguageFeatures",
        "WebTransport",
        "WebTransportBidirectionalStream",
        "WebTransportDatagramDuplexStream",
        "WebTransportError",
        "Worklet",
        "XRDOMOverlayState",
        "XRLayer",
        "XRWebGLBinding",
        "AudioData",
        "EncodedAudioChunk",
        "EncodedVideoChunk",
        "ImageTrack",
        "ImageTrackList",
        "VideoColorSpace",
        "VideoFrame",
        "AudioDecoder",
        "AudioEncoder",
        "ImageDecoder",
        "VideoDecoder",
        "VideoEncoder",
        "AuthenticatorAssertionResponse",
        "AuthenticatorAttestationResponse",
        "AuthenticatorResponse",
        "PublicKeyCredential",
        "Bluetooth",
        "BluetoothCharacteristicProperties",
        "BluetoothDevice",
        "BluetoothRemoteGATTCharacteristic",
        "BluetoothRemoteGATTDescriptor",
        "BluetoothRemoteGATTServer",
        "BluetoothRemoteGATTService",
        "CaptureController",
        "DocumentPictureInPicture",
        "EyeDropper",
        "Fence",
        "FencedFrameConfig",
        "HTMLFencedFrameElement",
        "FileSystemDirectoryHandle",
        "FileSystemFileHandle",
        "FileSystemHandle",
        "FileSystemWritableFileStream",
        "FontData",
        "FragmentDirective",
        "HID",
        "HIDConnectionEvent",
        "HIDDevice",
        "HIDInputReportEvent",
        "IdentityCredential",
        "IdentityProvider",
        "IdleDetector",
        "LaunchParams",
        "LaunchQueue",
        "OTPCredential",
        "PaymentAddress",
        "PaymentRequest",
        "PaymentResponse",
        "PaymentMethodChangeEvent",
        "Presentation",
        "PresentationAvailability",
        "PresentationConnection",
        "PresentationConnectionAvailableEvent",
        "PresentationConnectionCloseEvent",
        "PresentationConnectionList",
        "PresentationReceiver",
        "PresentationRequest",
        "Serial",
        "SerialPort",
        "SharedStorage",
        "SharedStorageWorklet",
        "ToggleEvent",
        "USB",
        "USBAlternateInterface",
        "USBConfiguration",
        "USBConnectionEvent",
        "USBDevice",
        "USBEndpoint",
        "USBInTransferResult",
        "USBInterface",
        "USBIsochronousInTransferPacket",
        "USBIsochronousInTransferResult",
        "USBIsochronousOutTransferPacket",
        "USBIsochronousOutTransferResult",
        "USBOutTransferResult",
        "WakeLock",
        "WakeLockSentinel",
        "WindowControlsOverlay",
        "WindowControlsOverlayGeometryChangeEvent",
        "XRAnchor",
        "XRAnchorSet",
        "XRBoundedReferenceSpace",
        "XRCPUDepthInformation",
        "XRCamera",
        "XRDepthInformation",
        "XRFrame",
        "XRHitTestResult",
        "XRHitTestSource",
        "XRInputSource",
        "XRInputSourceArray",
        "XRInputSourceEvent",
        "XRInputSourcesChangeEvent",
        "XRLightEstimate",
        "XRLightProbe",
        "XRPose",
        "XRRay",
        "XRReferenceSpace",
        "XRReferenceSpaceEvent",
        "XRRenderState",
        "XRRigidTransform",
        "XRSession",
        "XRSessionEvent",
        "XRSpace",
        "XRSystem",
        "XRTransientInputHitTestResult",
        "XRTransientInputHitTestSource",
        "XRView",
        "XRViewerPose",
        "XRViewport",
        "XRWebGLDepthInformation",
        "XRWebGLLayer",
        "getScreenDetails",
        "openDatabase",
        "queryLocalFonts",
        "showDirectoryPicker",
        "showOpenFilePicker",
        "showSaveFilePicker",
        "originAgentCluster",
        "credentialless",
        "speechSynthesis",
        "oncontentvisibilityautostatechange",
        "onscrollend",
        "AnimationPlaybackEvent",
        "AnimationTimeline",
        "CSSAnimation",
        "CSSTransition",
        "DocumentTimeline",
        "BackgroundFetchManager",
        "BackgroundFetchRecord",
        "BackgroundFetchRegistration",
        "BluetoothUUID",
        "BrowserCaptureMediaStreamTrack",
        "CropTarget",
        "CSSStartingStyleRule",
        "ContentVisibilityAutoStateChangeEvent",
        "DelegatedInkTrailPresenter",
        "Ink",
        "DocumentPictureInPictureEvent",
        "Highlight",
        "HighlightRegistry",
        "MediaMetadata",
        "MediaSession",
        "MutationEvent",
        "NavigatorUAData",
        "Notification",
        "PaymentManager",
        "PaymentRequestUpdateEvent",
        "PeriodicSyncManager",
        "PermissionStatus",
        "Permissions",
        "PushManager",
        "PushSubscription",
        "PushSubscriptionOptions",
        "RemotePlayback",
        "ScrollTimeline",
        "ViewTimeline",
        "SharedWorker",
        "SpeechSynthesisErrorEvent",
        "SpeechSynthesisEvent",
        "SpeechSynthesisUtterance",
        "VideoPlaybackQuality",
        "ViewTransition",
        "VisibilityStateEntry",
        "webkitSpeechGrammar",
        "webkitSpeechGrammarList",
        "webkitSpeechRecognition",
        "webkitSpeechRecognitionError",
        "webkitSpeechRecognitionEvent",
        "webkitRequestFileSystem",
        "webkitResolveLocalFileSystemURL"
    ],

    // @event: 407
    "68c": [
        [
            "loadTimes",
            "csi",
            "app"
        ],
        35,
        34,
        null,
        false,
        false,
        true,
        37,
        true,
        true,
        true,
        true,
        true,
        [
            "Raven",
            "_sharedLibs",
            "hsw"
        ],
        [
            [
                "getElementsByClassName",
                []
            ],
            [
                "getElementById",
                []
            ],
            [
                "querySelector",
                []
            ],
            [
                "querySelectorAll",
                []
            ]
        ],
        [],
        true
    ],

    // @event: 412
    "07a": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        true
    ],

    // @event: 2402
    "29e": [
        "Google Inc. (NVIDIA)",
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
    ],

    // @event: 2420
    "e02": [
        [
            "Z5r2dOyKtbZVQtlCmYUsQMVNLwItjZd2",
            "12",
            "1b",
            "PROJBSNMATXKY"
        ],
        [
            "L2z4NDSXEDmyucWTBjmLmDm2ADmyuiVYJEmyuySPP0C2dWawItJSPVtI1uRwItJoILWNhutFNkmLAjmLukulBVS=g0mIFtmPAjmLq3dfVZxwmkmLAjmLo3dfVZxwAjmLgub2",
            "4",
            "2d",
            "QPLQCMUPZZXLT"
        ]
    ],

    // @event: 2403
    "3a5": [
        "Google Inc. (NVIDIA)",
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
    ],

    // @event: 2401
    "b38": [
        [
            [
                "Google Inc. (NVIDIA)",
                "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
            ],
            [
                "ANGLE_instanced_arrays",
                "EXT_blend_minmax",
                "EXT_color_buffer_half_float",
                "EXT_disjoint_timer_query",
                "EXT_float_blend",
                "EXT_frag_depth",
                "EXT_shader_texture_lod",
                "EXT_texture_compression_bptc",
                "EXT_texture_compression_rgtc",
                "EXT_texture_filter_anisotropic",
                "EXT_sRGB",
                "KHR_parallel_shader_compile",
                "OES_element_index_uint",
                "OES_fbo_render_mipmap",
                "OES_standard_derivatives",
                "OES_texture_float",
                "OES_texture_float_linear",
                "OES_texture_half_float",
                "OES_texture_half_float_linear",
                "OES_vertex_array_object",
                "WEBGL_color_buffer_float",
                "WEBGL_compressed_texture_s3tc",
                "WEBGL_compressed_texture_s3tc_srgb",
                "WEBGL_debug_renderer_info",
                "WEBGL_debug_shaders",
                "WEBGL_depth_texture",
                "WEBGL_draw_buffers",
                "WEBGL_lose_context",
                "WEBGL_multi_draw"
            ],
            [
                [
                    1,
                    1024
                ],
                [
                    1,
                    1
                ],
                2147483647,
                2147483647,
                2147483647,
                2147483647,
                16384,
                [
                    32767,
                    32767
                ],
                4,
                16,
                4095,
                30,
                32,
                16,
                16,
                1024,
                "WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)",
                "WebKit",
                "WebKit WebGL",
                "WebGL 1.0 (OpenGL ES 2.0 Chromium)",
                16384,
                16384,
                [
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        0,
                        30,
                        31
                    ]
                ],
                [
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        0,
                        30,
                        31
                    ]
                ],
                16,
                8,
                true
            ]
        ],
        [
            [
                "Google Inc. (NVIDIA)",
                "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)"
            ],
            [
                "EXT_color_buffer_float",
                "EXT_color_buffer_half_float",
                "EXT_disjoint_timer_query_webgl2",
                "EXT_float_blend",
                "EXT_texture_compression_bptc",
                "EXT_texture_compression_rgtc",
                "EXT_texture_filter_anisotropic",
                "EXT_texture_norm16",
                "KHR_parallel_shader_compile",
                "OES_draw_buffers_indexed",
                "OES_texture_float_linear",
                "OVR_multiview2",
                "WEBGL_compressed_texture_s3tc",
                "WEBGL_compressed_texture_s3tc_srgb",
                "WEBGL_debug_renderer_info",
                "WEBGL_debug_shaders",
                "WEBGL_lose_context",
                "WEBGL_multi_draw",
                "WEBGL_provoking_vertex"
            ],
            [
                [
                    1,
                    1024
                ],
                [
                    1,
                    1
                ],
                2147483647,
                2147483647,
                2147483647,
                2147483647,
                16384,
                [
                    32767,
                    32767
                ],
                4,
                16,
                4095,
                30,
                32,
                16,
                16,
                1024,
                "WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)",
                "WebKit",
                "WebKit WebGL",
                "WebGL 2.0 (OpenGL ES 3.0 Chromium)",
                16384,
                16384,
                2048,
                2147483647,
                2147483647,
                2,
                8,
                4096,
                16380,
                2048,
                7,
                120,
                4,
                120,
                4,
                8,
                8,
                12,
                12,
                24,
                24,
                65536,
                212988,
                200704,
                120,
                120,
                4294967294,
                [
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        0,
                        30,
                        31
                    ]
                ],
                [
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        23,
                        127,
                        127
                    ],
                    [
                        0,
                        30,
                        31
                    ]
                ],
                16,
                null,
                true
            ]
        ]
    ],

    // @event: 2408
    "da4": true,

    // @event: 2407
    "3c5": [
        0,
        1,
        2,
        4,
        7,
        8,
        12,
        16,
        23,
        24,
        30,
        32,
        120,
        127,
        1024,
        2048,
        4095,
        4096,
        16380,
        16384,
        32767,
        65536,
        200704,
        212988,
        2147483647,
        4294967294
    ],

    // @event: 2409
    "b61": [
        2147483647,
        2147483647,
        4294967294
    ],

    // @event: 2411
    "e7d": [
        32767,
        32767,
        16384,
        8,
        8,
        8
    ],

    // @event: 2413
    "d5a": [
        2147483647,
        2147483647,
        2147483647,
        2147483647
    ],

    // @event: 2414
    "1f9": [
        16384,
        32,
        16384,
        2048,
        2,
        2048
    ],

    // @event: 2415
    "45a": [
        4,
        120,
        4
    ],

    // @event: 2416
    "a25": [
        24,
        24,
        65536,
        212988,
        200704
    ],

    // @event: 2417
    "026": [
        16,
        4095,
        30,
        16,
        16380,
        120,
        12,
        120,
        [
            23,
            127,
            127
        ]
    ],

    // @event: 905
    "f20": [
        [
            true,
            "fr-FR",
            true,
            "Microsoft Hortense - French (France)",
            "Microsoft Hortense - French (France)"
        ],
        [
            false,
            "fr-FR",
            true,
            "Microsoft Julie - French (France)",
            "Microsoft Julie - French (France)"
        ],
        [
            false,
            "fr-FR",
            true,
            "Microsoft Paul - French (France)",
            "Microsoft Paul - French (France)"
        ],
        [
            false,
            "de-DE",
            false,
            "Google Deutsch",
            "Google Deutsch"
        ],
        [
            false,
            "en-US",
            false,
            "Google US English",
            "Google US English"
        ],
        [
            false,
            "en-GB",
            false,
            "Google UK English Female",
            "Google UK English Female"
        ],
        [
            false,
            "en-GB",
            false,
            "Google UK English Male",
            "Google UK English Male"
        ],
        [
            false,
            "es-ES",
            false,
            "Google español",
            "Google español"
        ],
        [
            false,
            "es-US",
            false,
            "Google español de Estados Unidos",
            "Google español de Estados Unidos"
        ],
        [
            false,
            "fr-FR",
            false,
            "Google français",
            "Google français"
        ],
        [
            false,
            "hi-IN",
            false,
            "Google हिन्दी",
            "Google हिन्दी"
        ],
        [
            false,
            "id-ID",
            false,
            "Google Bahasa Indonesia",
            "Google Bahasa Indonesia"
        ],
        [
            false,
            "it-IT",
            false,
            "Google italiano",
            "Google italiano"
        ],
        [
            false,
            "ja-JP",
            false,
            "Google 日本語",
            "Google 日本語"
        ],
        [
            false,
            "ko-KR",
            false,
            "Google 한국의",
            "Google 한국의"
        ],
        [
            false,
            "nl-NL",
            false,
            "Google Nederlands",
            "Google Nederlands"
        ],
        [
            false,
            "pl-PL",
            false,
            "Google polski",
            "Google polski"
        ],
        [
            false,
            "pt-BR",
            false,
            "Google português do Brasil",
            "Google português do Brasil"
        ],
        [
            false,
            "ru-RU",
            false,
            "Google русский",
            "Google русский"
        ],
        [
            false,
            "zh-CN",
            false,
            "Google 普通话（中国大陆）",
            "Google 普通话（中国大陆）"
        ],
        [
            false,
            "zh-HK",
            false,
            "Google 粤語（香港）",
            "Google 粤語（香港）"
        ],
        [
            false,
            "zh-TW",
            false,
            "Google 國語（臺灣）",
            "Google 國語（臺灣）"
        ]
    ],

    // @event: 905
    "e03": [
        [
            true,
            "fr-FR",
            true,
            "Microsoft Hortense - French (France)",
            "Microsoft Hortense - French (France)"
        ],
        [
            false,
            "fr-FR",
            true,
            "Microsoft Julie - French (France)",
            "Microsoft Julie - French (France)"
        ],
        [
            false,
            "fr-FR",
            true,
            "Microsoft Paul - French (France)",
            "Microsoft Paul - French (France)"
        ]
    ],

    // @event: 1302
    "39b": [
        0,
        1,
        2,
        3,
        4
    ],

    // @event: 1904
    "fd2": [
        0,
        11411,
        11411
    ],

    // @event: 702
    "1a3": [
        "Windows",
        "15.0.0",
        null,
        "64",
        "x86",
        "117.0.5938.92"
    ],

    // @event: 3210
    "c0d": [
        143254600089,
        143254600089,
        null,
        null,
        4294705152,
        true,
        true,
        true,
        null
    ],

    // @event: 2001
    "7ec": [
        "granted",
        "TypeError",
        "TypeError",
        "prompt",
        "granted",
        "TypeError",
        "denied",
        "TypeError",
        "denied",
        "denied",
        "TypeError",
        "denied",
        "TypeError",
        "denied",
        "granted",
        "denied",
        "granted",
        "denied",
        "denied",
        "TypeError",
        "denied",
        "granted",
        "denied",
        "prompt",
        "NotSupportedError",
        "denied",
        "TypeError",
        "TypeError",
        "TypeError",
        "denied"
    ],

    // @event: 2002
    "7b7": [
        "denied",
        "denied"
    ],

    // @event: 0
    "02f": 66.10000000149012
}