/* Automatically generated by wasm2c */
#ifndef TEST_H_GENERATED_
#define TEST_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_0x2E0x2Fclient__bg0x2Ejs;

typedef struct w2c_main {
  struct w2c_0x2E0x2Fclient__bg0x2Ejs* w2c_0x2E0x2Fclient__bg0x2Ejs_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_wbindgen_export_2;
} w2c_main;

void wasm2c_main_instantiate(w2c_main*, struct w2c_0x2E0x2Fclient__bg0x2Ejs*);
void wasm2c_main_free(w2c_main*);
wasm_rt_func_type_t wasm2c_main_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: '.\2Fclient_bg.js' '__wbg_availHeight_5a38eff40ca35e9b' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_availHeight_5a38eff40ca35e9b(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_availWidth_52ce20c430bfe00d' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_availWidth_52ce20c430bfe00d(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_beginPath_790cd831253a2637' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_beginPath_790cd831253a2637(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_buffer_eb2155f17856c20b' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_buffer_eb2155f17856c20b(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_call_4438b4bab9ab5268' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_call_4438b4bab9ab5268(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_call_9698e9b9c4668ae0' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_call_9698e9b9c4668ae0(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_call_f325895c60cbae4d' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_call_f325895c60cbae4d(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_colorDepth_2dc95ec7a52b996f' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_colorDepth_2dc95ec7a52b996f(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_construct_8fcba71a7eab4ec1' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_construct_8fcba71a7eab4ec1(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_createElement_1959ce882284e011' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_createElement_1959ce882284e011(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_crypto_b8c92eaac23d0d80' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_crypto_b8c92eaac23d0d80(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_data_94533a8c9648f5a1' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_data_94533a8c9648f5a1(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_defineProperty_c324da7a0b2d7d18' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_defineProperty_c324da7a0b2d7d18(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_documentElement_3932e3004b15af7f' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_documentElement_3932e3004b15af7f(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_document_6d5890b86bbf5b96' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_document_6d5890b86bbf5b96(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_errors_cf2f48b8817772d8' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_errors_cf2f48b8817772d8(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_fillStyle_3d31d929bbe8a2f5' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_fillStyle_3d31d929bbe8a2f5(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_fillText_fdd6d14e79f143f3' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_fillText_fdd6d14e79f143f3(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32, f64, f64);

/* import: '.\2Fclient_bg.js' '__wbg_getContext_c91489f5e0f738d8' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_getContext_c91489f5e0f738d8(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_getElementById_f059b7401a23ee7c' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_getElementById_f059b7401a23ee7c(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_getEntriesByType_505aabfe19f2425b' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_getEntriesByType_505aabfe19f2425b(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_getOwnPropertyDescriptor_24aa7e693dd9e2da' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_getOwnPropertyDescriptor_24aa7e693dd9e2da(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_getRandomValues_dd27e6b0652b3236' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_getRandomValues_dd27e6b0652b3236(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_getRandomValues_e57c9b75ddead065' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_getRandomValues_e57c9b75ddead065(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_get_75d36ef8b2e1d918' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_get_75d36ef8b2e1d918(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_get_a4f61a2fb16987bc' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_get_a4f61a2fb16987bc(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_get_e7022d8fa5682598' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_get_e7022d8fa5682598(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_globalThis_787cfd4f25a35141' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_globalThis_787cfd4f25a35141(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_global_af2eb7b1369372ed' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_global_af2eb7b1369372ed(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_hasAttribute_c831cb47fd0a093a' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_hasAttribute_c831cb47fd0a093a(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_has_d87073f723676bd5' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_has_d87073f723676bd5(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_height_ec1147d0b6442a92' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_height_ec1147d0b6442a92(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_indexedDB_acff057640f0088f' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_indexedDB_acff057640f0088f(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_initiatorType_b076fd08af0e9a48' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_initiatorType_b076fd08af0e9a48(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_instanceof_CanvasRenderingContext2d_cf60543e642e5a93' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_instanceof_CanvasRenderingContext2d_cf60543e642e5a93(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_instanceof_Error_ac0db369f0645066' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_instanceof_Error_ac0db369f0645066(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_instanceof_HtmlCanvasElement_a2acc34cc0a30700' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_instanceof_HtmlCanvasElement_a2acc34cc0a30700(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_instanceof_PerformanceResourceTiming_08731e9d5b731334' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_instanceof_PerformanceResourceTiming_08731e9d5b731334(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_instanceof_Uint8Array_2ef9531f7c172ac9' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_instanceof_Uint8Array_2ef9531f7c172ac9(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_instanceof_Window_b99429ec408dcb8d' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_instanceof_Window_b99429ec408dcb8d(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_keys_8f13118772d7b32c' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_keys_8f13118772d7b32c(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_language_f050e03d2e52b258' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_language_f050e03d2e52b258(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_length_0b194abde938d0c6' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_length_0b194abde938d0c6(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_length_f86925e8c69110ea' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_length_f86925e8c69110ea(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_loadTimes_4e24ad5f8e3d2884' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_loadTimes_4e24ad5f8e3d2884(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_localStorage_fbbeeb3a3dfd5be3' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_localStorage_fbbeeb3a3dfd5be3(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_messages_44a8919b69fcd299' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_messages_44a8919b69fcd299(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_msCrypto_9ad6677321a08dd8' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_msCrypto_9ad6677321a08dd8(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_name_0b33b0c5c78f20db' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_name_0b33b0c5c78f20db(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_navigator_bc0b459c4b6dbe01' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_navigator_bc0b459c4b6dbe01(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_new_ae366b99da42660b' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_new_ae366b99da42660b(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_new_d4a8512c351e5299' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_new_d4a8512c351e5299(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_new_ff8b26f7b2d7e2fb' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_new_ff8b26f7b2d7e2fb(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_new_ffb8fbe0ad5d4d2f' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_new_ffb8fbe0ad5d4d2f(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_newnoargs_68424965d85fcb08' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_newnoargs_68424965d85fcb08(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_newwithlength_a49b32b2030b93c3' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_newwithlength_a49b32b2030b93c3(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_now_0f688205547f47a2' */
f64 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_now_0f688205547f47a2(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_origin_566065d052266ba1' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_origin_566065d052266ba1(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_ownKeys_df13b91d66111202' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_ownKeys_df13b91d66111202(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_performance_b21afb8a0a7e3e9a' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_performance_b21afb8a0a7e3e9a(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_pixelDepth_c6ae77d65aa9cf0a' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_pixelDepth_c6ae77d65aa9cf0a(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_platform_1e434a0f557294e0' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_platform_1e434a0f557294e0(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_plugins_320bace199ef9abf' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_plugins_320bace199ef9abf(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_randomFillSync_d2ba53160aec6aba' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_randomFillSync_d2ba53160aec6aba(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_require_f5521a5b85ad2542' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_require_f5521a5b85ad2542(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_resolve_84f06d050082a771' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_resolve_84f06d050082a771(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_screen_563041f109418bcc' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_screen_563041f109418bcc(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_self_3df7c33e222cd53b' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_self_3df7c33e222cd53b(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_self_86b4b13392c7af56' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_self_86b4b13392c7af56(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_sessionStorage_305af71f8a4df982' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_sessionStorage_305af71f8a4df982(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_set_67cdd115b9cb141f' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_set_67cdd115b9cb141f(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_set_c7fc8735d70ceb11' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_set_c7fc8735d70ceb11(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_slice_b091b14e7766c812' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_slice_b091b14e7766c812(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_static_accessor_MODULE_452b4680e8614c81' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_static_accessor_MODULE_452b4680e8614c81(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbg_stringify_bc3c2afd0dba3362' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_stringify_bc3c2afd0dba3362(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_stroke_cd9ee78b96e12894' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_stroke_cd9ee78b96e12894(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_subarray_1bb315d30e0c968c' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_subarray_1bb315d30e0c968c(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_then_c919ca41618a24c2' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_then_c919ca41618a24c2(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_then_fd35af33296a58d7' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_then_fd35af33296a58d7(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_toDataURL_fe2ebea8b463e5de' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_toDataURL_fe2ebea8b463e5de(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_toString_b2da48ab6ca0c44d' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_toString_b2da48ab6ca0c44d(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_toString_f0c7462ac29ba762' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_toString_f0c7462ac29ba762(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_userAgent_9206fc4778d7ddbf' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_userAgent_9206fc4778d7ddbf(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbg_width_85d397e0585a43f5' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_width_85d397e0585a43f5(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbg_window_0f90182e6c405ff2' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbg_window_0f90182e6c405ff2(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbindgen_cb_drop' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_cb_drop(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_closure_wrapper153' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_closure_wrapper153(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_closure_wrapper155' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_closure_wrapper155(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_closure_wrapper373' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_closure_wrapper373(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_debug_string' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_debug_string(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_is_function' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_is_function(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_is_object' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_is_object(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_is_undefined' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_is_undefined(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_json_parse' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_json_parse(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_json_serialize' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_json_serialize(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_jsval_eq' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_jsval_eq(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_memory' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_memory(struct w2c_0x2E0x2Fclient__bg0x2Ejs*);

/* import: '.\2Fclient_bg.js' '__wbindgen_number_get' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_number_get(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_object_clone_ref' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_object_clone_ref(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_object_drop_ref' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_object_drop_ref(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_rethrow' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_rethrow(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_string_get' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_string_get(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_string_new' */
u32 w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_string_new(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* import: '.\2Fclient_bg.js' '__wbindgen_throw' */
void w2c_0x2E0x2Fclient__bg0x2Ejs_0x5F_wbindgen_throw(struct w2c_0x2E0x2Fclient__bg0x2Ejs*, u32, u32);

/* export: '__wbindgen_export_2' */
wasm_rt_funcref_table_t* w2c_main_0x5F_wbindgen_export_2(w2c_main* instance);

/* export: 'memory' */
wasm_rt_memory_t* w2c_main_memory(w2c_main* instance);

/* export: 'client' */
u32 w2c_main_client(w2c_main*, u32, u32, u32, u32, u32, u32);

/* export: '_dyn_core__ops__function__FnMut__A_B___Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h73dd969f219abd8f' */
u32 w2c_main_0x5Fdyn_core_0x5Fops_0x5Ffunction_0x5FFnMut_0x5FA_B_0x5F_Output_0x5F_R_as_wasm_bindgen_0x5Fclosure_0x5FWasmClosure_0x5F_describe_0x5Finvoke_0x5Fh73dd969f219abd8f(w2c_main*, u32, u32, u32, u32);

/* export: '__wbindgen_malloc' */
u32 w2c_main_0x5F_wbindgen_malloc(w2c_main*, u32);

/* export: '__wbindgen_realloc' */
u32 w2c_main_0x5F_wbindgen_realloc(w2c_main*, u32, u32, u32);

/* export: '_dyn_core__ops__function__FnMut__A_B___Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h7a34a6e3a13907a7' */
void w2c_main_0x5Fdyn_core_0x5Fops_0x5Ffunction_0x5FFnMut_0x5FA_B_0x5F_Output_0x5F_R_as_wasm_bindgen_0x5Fclosure_0x5FWasmClosure_0x5F_describe_0x5Finvoke_0x5Fh7a34a6e3a13907a7(w2c_main*, u32, u32, u32, u32);

/* export: 'wasm_bindgen__convert__closures__invoke2_mut__h676e1c56b2ccb8ff' */
void w2c_main_wasm_bindgen_0x5Fconvert_0x5Fclosures_0x5Finvoke2_mut_0x5Fh676e1c56b2ccb8ff(w2c_main*, u32, u32, u32, u32);

/* export: '_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3abaaf06c02a2a6c' */
void w2c_main_0x5Fdyn_core_0x5Fops_0x5Ffunction_0x5FFnMut_0x5FA_0x5F_0x5FOutput_0x5F_R_as_wasm_bindgen_0x5Fclosure_0x5FWasmClosure_0x5F_describe_0x5Finvoke_0x5Fh3abaaf06c02a2a6c(w2c_main*, u32, u32, u32);

/* export: '__wbindgen_exn_store' */
void w2c_main_0x5F_wbindgen_exn_store(w2c_main*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* TEST_H_GENERATED_ */
